# Generated by Django 4.2.13 on 2024-05-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="RestaurantInfo", new_name="RestaurantInfo1",),
    ]
