# Generated by Django 4.2.13 on 2024-05-28 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookmark", "0003_rename_restaurantinfo_restaurantinfo1"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark", unique_together={("user", "name")},
        ),
    ]
