# Generated by Django 4.2.13 on 2024-05-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0004_alter_bookmark_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantinfo1",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="restaurantinfo1",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
